chi = float(input("What is the price of a child's meal?"))
adu = float(input("What is the price of an adult's meal? "))
chiNum = int(input('How many children are there? '))
aduNum = int(input('How many adults are there? '))
tax = float(input('What is the sales tax rate? '))

chiPri = (chi*chiNum)
aduPri = (adu*aduNum)
subTotal = (chiPri+aduPri)
subReduced = '${:.2f}'.format(subTotal)
taxTotal = (subTotal*(tax/100))
taxTotalReduced = '${:.2f}'.format(taxTotal)
print()
print('Subtotal:',subReduced)
print('Sales tax:',taxTotalReduced)
price = (subTotal+ taxTotal)
priceReduced = '${:.2f}'.format(price)
print('Total Price:',priceReduced)
print()
cash  = int(input('What is the payment amount? '))
cashReduced = '${:.2f}'.format(cash)
change = (cash - price)
changeReduced = '${:.2f}'.format(change)

print(f'Change:',changeReduced)
